
import type { Expedition } from "@/lib/types";

export const expeditions: Expedition[] = [
  {
    id: "exp-001",
    name: "1st Indian Antarctic Expedition",
    season: "1981–82",
    year: 1981,
    region: "Antarctica",
    station: "Dakshin Gangotri (site selection)",
    leader: "Dr. S. Z. Qasim",
    teamSize: 21,
    description:
      "India's first voyage to Antarctica, marking the country's entry into Antarctic research. The team conducted a multi-disciplinary reconnaissance of the Dronning Maud Land coast and selected the site for India's first station.",
    objectives: [
      "Reconnaissance of the Princess Astrid Coast",
      "Site selection for a permanent research station",
      "Pilot studies in oceanography, biology and geology",
    ],
    researchAreas: ["Oceanography", "Marine Biology", "Geology"],
    reports: [],
    publications: [],
    ongoing: false,
  },
  {
    id: "exp-002",
    name: "Dakshin Gangotri Establishment Expedition",
    season: "1983–84",
    year: 1983,
    region: "Antarctica",
    station: "Dakshin Gangotri",
    leader: "Dr. V. K. Raina",
    teamSize: 28,
    description:
      "The expedition that established Dakshin Gangotri — 'Ganga of the South' — India's first Antarctic research station, commissioned in January 1984 near the Larsemann Hills.",
    objectives: [
      "Construct and commission Dakshin Gangotri station",
      "Initiate year-round meteorological observations",
      "Begin geological mapping of the Schirmacher Oasis",
    ],
    researchAreas: ["Meteorology", "Geology", "Glaciology"],
    reports: [],
    publications: [],
    ongoing: false,
  },
  {
    id: "exp-003",
    name: "Maitri Commissioning Expedition",
    season: "1988–89",
    year: 1989,
    region: "Antarctica",
    station: "Maitri",
    leader: "Dr. H. P. S. Ahluwalia",
    teamSize: 34,
    description:
      "Established Maitri station in the Schirmacher Oasis, replacing the snow-buried Dakshin Gangotri and giving India a modern, year-round Antarctic research capability.",
    objectives: [
      "Commission the Maitri research station",
      "Expand the automatic weather station network",
      "Launch continuous atmospheric chemistry observations",
    ],
    researchAreas: ["Meteorology", "Atmospheric Science", "Earth Sciences"],
    reports: [],
    publications: [],
    ongoing: false,
  },
  {
    id: "exp-004",
    name: "Himadri Arctic Programme Commences",
    season: "2007–08",
    year: 2008,
    region: "Arctic",
    station: "Himadri",
    leader: "NCPOR Arctic Cell",
    teamSize: 12,
    description:
      "India opened its Arctic research station Himadri at Ny-Ålesund, Svalbard, extending Indian polar science to both ends of the Earth and joining international Arctic observing networks.",
    objectives: [
      "Establish a permanent Arctic observation presence",
      "Begin aerosol and cryosphere time series",
      "Join coordinated international Arctic programmes",
    ],
    researchAreas: ["Atmospheric Science", "Glaciology", "Arctic Oceanography"],
    reports: [],
    publications: [],
    ongoing: false,
  },
  {
    id: "exp-005",
    name: "Bharati Commissioning Expedition",
    season: "2011–12",
    year: 2012,
    region: "Antarctica",
    station: "Bharati",
    leader: "Dr. A. A. Mohammed",
    teamSize: 46,
    description:
      "Commissioned Bharati, India's third Antarctic station in the Larsemann Hills — a state-of-the-art facility focused on the Indian Ocean sector of East Antarctica.",
    objectives: [
      "Commission the Bharati research station",
      "Initiate Prydz Bay oceanographic time series",
      "Establish satellite Earth-observation receiving capabilities",
    ],
    researchAreas: ["Oceanography", "Earth Observation", "Glaciology"],
    reports: [],
    publications: [],
    ongoing: false,
  },
  {
    id: "exp-006",
    name: "40th Indian Antarctic Expedition",
    season: "2019–20",
    year: 2019,
    region: "Antarctica",
    station: "Maitri / Bharati",
    leader: "Dr. S. K. Singh",
    teamSize: 90,
    description:
      "The milestone 40th expedition celebrated four decades of Indian Antarctic research with an expanded outreach programme, a new atmospheric chemistry laboratory at Maitri, and the pilot krill acoustic survey in Prydz Bay.",
    objectives: [
      "Commemorate 40 years of Indian Antarctic research",
      "Commission atmospheric chemistry laboratory",
      "Launch Prydz Bay krill time series",
    ],
    researchAreas: ["Atmospheric Science", "Marine Biology", "Polar Ecology"],
    reports: ["res-015"],
    publications: ["res-006", "res-009"],
    ongoing: false,
  },
  {
    id: "exp-007",
    name: "43rd Indian Antarctic Expedition",
    season: "2023–24",
    year: 2023,
    region: "Antarctica",
    station: "Bharati / Maitri",
    leader: "Dr. R. Venkatesan",
    teamSize: 98,
    description:
      "A full-scale multidisciplinary season featuring the Prydz Bay ocean survey, wintering handover, and the human-physiology programme — alongside public engagement through the expedition video log.",
    objectives: [
      "Execute 47-station Prydz Bay multidisciplinary survey",
      "Hand over wintering operations at both stations",
      "Continue wintering team physiology study",
    ],
    researchAreas: ["Oceanography", "Human Biology", "Meteorology"],
    reports: ["res-012"],
    publications: ["res-002", "res-005", "res-010"],
    ongoing: false,
  },
  {
    id: "exp-008",
    name: "44th Indian Antarctic Expedition",
    season: "2024–25",
    year: 2024,
    region: "Antarctica",
    station: "Bharati / Maitri",
    leader: "Dr. M. Ravichandran (Programme Director)",
    teamSize: 101,
    description:
      "The latest chapter of India's Antarctic programme: 42 science projects across six disciplines, continued long-term observing commitments, and the annual resupply traverse to both stations.",
    objectives: [
      "Operate 42 science projects across six disciplines",
      "Complete annual resupply traverse to Bharati and Maitri",
      "Maintain continuity of 30+ long-term observational series",
    ],
    researchAreas: [
      "Oceanography",
      "Glaciology",
      "Atmospheric Science",
      "Climate Science",
      "Marine Biology",
      "Earth Observation",
    ],
    reports: ["res-011"],
    publications: ["res-003"],
    ongoing: true,
  },
];

export const timeline = [
  { year: "1981", title: "First Indian Antarctic Expedition", text: "A 21-member team aboard the M/V Trishna opens India's Antarctic chapter." },
  { year: "1983", title: "Dakshin Gangotri Established", text: "India's first station, 'Ganga of the South', commissioned in Dronning Maud Land." },
  { year: "1989", title: "Maitri Station", text: "A modern year-round station commissioned in the Schirmacher Oasis." },
  { year: "2008", title: "Himadri, Svalbard", text: "India extends its reach to the Arctic with a station at Ny-Ålesund." },
  { year: "2012", title: "Bharati Station", text: "A state-of-the-art facility rises in the Larsemann Hills." },
  { year: "2019", title: "40th Expedition", text: "Four decades of Antarctic research celebrated." },
  { year: "2024", title: "44th Expedition", text: "42 science projects continue India's polar legacy." },
];

export function getExpedition(id: string): Expedition | undefined {
  return expeditions.find((e) => e.id === id);
}
